/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as TechsIndexRouteImport } from './routes/techs.index'
import { Route as TechsTechIdRouteImport } from './routes/techs.$techId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const TechsIndexRoute = TechsIndexRouteImport.update({
  id: '/techs/',
  path: '/techs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechsTechIdRoute = TechsTechIdRouteImport.update({
  id: '/techs/$techId',
  path: '/techs/$techId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disputes': typeof DisputesRoute
  '/invoices': typeof InvoicesRoute
  '/techs/$techId': typeof TechsTechIdRoute
  '/techs/': typeof TechsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disputes': typeof DisputesRoute
  '/invoices': typeof InvoicesRoute
  '/techs/$techId': typeof TechsTechIdRoute
  '/techs': typeof TechsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disputes': typeof DisputesRoute
  '/invoices': typeof InvoicesRoute
  '/techs/$techId': typeof TechsTechIdRoute
  '/techs/': typeof TechsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disputes' | '/invoices' | '/techs/$techId' | '/techs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disputes' | '/invoices' | '/techs/$techId' | '/techs'
  id:
    '__root__' | '/' | '/disputes' | '/invoices' | '/techs/$techId' | '/techs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisputesRoute: typeof DisputesRoute
  InvoicesRoute: typeof InvoicesRoute
  TechsTechIdRoute: typeof TechsTechIdRoute
  TechsIndexRoute: typeof TechsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/techs/': {
      id: '/techs/'
      path: '/techs'
      fullPath: '/techs/'
      preLoaderRoute: typeof TechsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/techs/$techId': {
      id: '/techs/$techId'
      path: '/techs/$techId'
      fullPath: '/techs/$techId'
      preLoaderRoute: typeof TechsTechIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisputesRoute: DisputesRoute,
  InvoicesRoute: InvoicesRoute,
  TechsTechIdRoute: TechsTechIdRoute,
  TechsIndexRoute: TechsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
